### ISSUE TITLE
Segfault which is caused by flb_tls_context_destroy

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#112]
`flb_test_elasticsearch` is not finished successfully.

At `flb_output_init()`,  a variable `p->flags` is checked like bitmap.
```c
        if (p->flags & FLB_IO_TLS) {
            ins->tls.context = flb_tls_context_new(ins->tls_verify,
```

On the other hand, `FLB_IO_TLS` is defined like enum at `flb_io.h`.
``` c
/* Network operation modes */
#define FLB_IO_TCP         1  /* use plain TCP                          */
#define FLB_IO_TLS         2  /* use TLS/SSL layer                      */
#define FLB_IO_OPT_TLS     3  /* use TCP and optional TLS               */
#define FLB_IO_ASYNC       4  /* use async mode (depends on event loop) */
```

Which is proper ?
Now, `if (p->flags & FLB_IO_TLS) ` is true when p->flags is set FLB_IO_OPT_TLS (out_es sets like this).

**Comment by nokute78** [comment]
This also affects `out_es` and `out_http`.
Segfault occurs when Ctrl+C is sent.

**Comment by edsiper** [comment]
some background about the options:

- FLB_IO_TCP (implicit for every plugin) offers networking support for the plugin.
- FLB_IO_TLS enable TLS support in the plugin, but it's up to the plugin to re-enable the TLS contexts when the upstreams are created.
- FLB_IO_OPT_TLS means the plugin _may_ optionally use TLS, common use case is: out_http, it can use plain HTTP or use HTTPs.

FLB_OPT_TLS = 3 which is (FLB_IO_TCP  | FLB_IO_TLS) 

about the crash I am trying to reproduce now.

**Comment by edsiper** [comment]
I have not been able to reproduce the issue. 

note: I just pushed some fixes for 'retries' but I am not sure if that may be the root cause, would you please re-check ?

**Comment by nokute78** [comment]
It is not fixed newest commit 08c71aac3ac933c3ae359eb11119f30961952cd5.

This is how to reproduce .

* `$bin/fluent-bit -i cpu -o es` and Ctrl+C

However, I can not reproduce this issue "when using gdb".

This is a log.
```
$ bin/fluent-bit -i cpu -o es
Fluent-Bit v0.9.0
Copyright (C) Treasure Data

[2016/10/04 22:55:23] [ info] [engine] started
[2016/10/04 22:55:23] [error] [TLS] Invalid CA file: /etc/ssl/certs/ca-certificates.crt
[2016/10/04 22:55:23] [debug] [es] host=127.0.0.1 port=9200 index=fluentbit type=test
[2016/10/04 22:55:23] [debug] [router] default match rule cpu.0:es.0
[2016/10/04 22:55:28] [debug] [task] created task=0xf47f90 OK
[2016/10/04 22:55:28] [error] [io] TCP connection failed: 127.0.0.1:9200
[2016/10/04 22:55:28] [debug] [sched] retry=0xf48070 0 in 0 seconds
[2016/10/04 22:55:28] [error] [io] TCP connection failed: 127.0.0.1:9200
[2016/10/04 22:55:28] [debug] [sched] retry=0xf48070 0 in 2 seconds
^C[engine] caught signal
[2016/10/04 22:55:28] [debug] [task] destroy task=0xf47f90 (task_id=0)
Segmentation fault
```

**Comment by edsiper** [comment]
I was able to reproduce it:

- make sure TLS support exists but cannot be initiated (e.g: check your invalid CA file message)
- exit from a plugin using output with TLS

The core was always trying to release a TLS context but sometimes it may not be set due to some previous error.

Fixed by 5110bf11a916f412fb6a238655fac337dffa16fd

**Comment by nokute78** [comment]
Thanks!
