### ISSUE TITLE
Stdin plugin not working properly on Alpine linux 

### ISSUE THREAD

**Issue by adalrsjr1** [fluent/fluent-bit#145]
I've created a docker container with fluent-bit + alpine linux, however I attempt to run the example from site to pipe the script to fluent-bit stdin but it isn't work. Fluent bit not receive the script output.

test.sh
```
#!/bin/sh

while :; do
  echo -n "{\"key\": \"some value\"}"
  sleep 1
done
```

test.sh | fluent-bit -i stdin -o stdout

On Ubuntu works fine, only on alpine that I have this issue.

**Comment by edsiper** [comment]
would you please share the URL of your Dockerfile ?

**Comment by adalrsjr1** [comment]
My Dockerfile is below. I'm trying to run the script+fluent-bit interactively

`FROM openjdk:8-jdk-alpine

RUN apk --no-cache --update add gcc \
                                make \
				cmake \
				build-base \
				abuild \
				binutils \
				binutils-doc \
				gcc-doc \
				zlib-dev

RUN mkdir -p /home/fluent-bit && cd /home/fluent-bit && \
    wget http://fluentbit.io/releases/0.9/fluent-bit-0.9.0.tar.gz && \
    tar xzf fluent-bit-0.9.0.tar.gz && \
    rm fluent-bit-0.9.0.tar.gz && \
    cd fluent-bit-0.9.0 && \
    cmake . && make && make install

RUN mkdir -p /home/app
WORKDIR /home/app

ENTRYPOINT ["sh"]

`

**Comment by edsiper** [comment]
I just pushed an image based on Alpine, please give it a try and send me some feedback:

https://github.com/fluent/fluent-bit-docker

If for some reason you see some issue, please provide detailed steps to reproduce it.

**Comment by adalrsjr1** [comment]
The issue persist. I suspect that this problem could be related in some sense with the absence of glibc at Alpine linux. But this is a total guess.

Build: `docker build --rm -t fluentbit .`
Run: `docker run -it --rm --name fluentbit fluentbit`

in home folder `/home/fluent` I created a script named test.sh

```
#!/bin/sh

while :; do
  echo -n "{\"key\": \"some value\"}"
  sleep 1
done
```

make it executable `chmod +x test.sh` and run with fluent-bit:

`test.sh | fluent-bit -i stdin -o stdout -f 1`

It was expected a stream of outputs like this:

[2016/10/07 21:44:46] [ info] [engine] started
[0] stdin.0: [1475898286, {"key"=>"some value"}]
[1] stdin.0: [1475898287, {"key"=>"some value"}]
[2] stdin.0: [1475898288, {"key"=>"some value"}]
[3] stdin.0: [1475898289, {"key"=>"some value"}]
[4] stdin.0: [1475898290, {"key"=>"some value"}]

But nothing appear at screen below the header `[date][info][engine] started`. 

The same steps in a ubuntu xenial:latest container work fine.

My docker version is:
```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Comment by edsiper** [comment]
I found the problem. It was a missing variable initialization, the fix is here:

   https://github.com/fluent/fluent-bit/commit/513298818cafbdc89643fdbe9f85a5262a0b1c96

Shortly I will release Fluent Bit v0.9.1 with this fix and update the Docker repo. Thanks for your help!

**Comment by adalrsjr1** [comment]
Nice! now is working properly

**Comment by edsiper** [comment]
Fixed.
