### ISSUE TITLE
Duplicate Entries when 32+ inputs are configured

### ISSUE THREAD

**Issue by etm42** [fluent/fluent-bit#2914]
## Bug Report

**BACKGROUND**
* We're running amazon/aws-for-fluent-bit:2.10.0 docker container
* Input comes from the "tail" plugin
* Output goes into AWS CloudWatch using the "cloudwatch_logs" plugin

**PROBLEM**
Since upgrading to aws-for-fluent-bit:2.10.0 (from 2.1.0), we're getting duplicate entries in the cloudwatch streams, where some entries get duplicated and end up in a different stream within the same group.

**TROUBLESHOOTING**
I believe the problem lies with the tail INPUT plugin, with the issue is appearing in versions 2.8.0 and above of amazon/aws-for-fluent-bit. (I've tested against every version.)

The boundary between 2.7.0 and below (working) and 2.8.0 and above (broken) is described [here](https://github.com/aws/aws-for-fluent-bit/compare/v2.7.0...v2.8.0), mentioning the Fluent Bit component versions.

Testing has shown:
* The problem remains when switching from `cloudwatch_logs` OUTPUT plugin to `file` OUTPUT plugin (except the entries are duplicated to the same log and not to a different stream)
* Using the `file` output plugin and going back to aws-for-fluent-bit:2.7.0 and below solves the issue
* Simplifying our configuration, I can provide a very simple config the reproduces the problem (below)

**STEPS TO REPRODUCE**
1. Create `docker-compose.yml`, `parsers.conf` and `fluent-bit.conf` using the content below.

2. ```mkdir -p DL-5175/output DL-5175/test```

3. Delete previous state (input logs, output logs, databases) and re-create the container
```docker stop aws_fluentbit; sudo rm dbs/main*; docker rm aws_fluentbit; sudo find DL-5175/ -type f |sudo xargs -I{} rm {}; docker ps; docker-compose up -d; docker ps; sleep 1```

4. Send a test message to all input logs, with the log name in the message (so we know the source)
```grep -B3 Parser fluent-bit.conf |awk '/Path/ {print $2}' |sed 's%/logs%/opt/aws-fluent-bit/DL-5175%' |sort |while read log; do echo "${now} - DL-5175: TEST MESSAGE ADDED TO ${log} LOG" >> $log; done```

5. Wait a minute for some output logs to appear
```sleep 60```

6. Count how many output logs there are (expect 36 for 2.7.0 and below where it works fine)
```cat DL-5175/output/* |awk -F: '{print $1}' |sort |uniq -c |wc -l```

7. Count how many messages in each output log (expect 1-per-log for 2.7.0 and below where it works fine)
```cat DL-5175/output/* |awk -F: '{print $1}' |sort |uniq -c```

8. See the contents output log, so to closely examine any duplication
```cat DL-5175/output/*```

**docker-compse.yml**
```version: '2'
services:
  aws_fluentbit:
    image: amazon/aws-for-fluent-bit:2.10.0
    hostname: lenny
    container_name: aws_fluentbit
    restart: always
    environment: []
    volumes:
      # main config
      - /opt/aws-fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      # parsers
      - /opt/aws-fluent-bit/parsers.conf:/fluent-bit/parsers/parsers.conf
      # dbs folder
      - /opt/aws-fluent-bit/dbs:/dbs
      # folders mounted from profiles
      - /opt/aws-fluent-bit/DL-5175:/logs
```
**parsers.conf**
```[PARSER]
    Name        simple_parser
    Format      regex
    Regex       ^
```
**fluent-bit.conf**
```[SERVICE]
    Parsers_File        /fluent-bit/parsers/parsers.conf

[INPUT]
    Name                tail
    Path                /logs/test/file_0001.log
    Parser              simple_parser
    DB                  /dbs/main
    Tag                 tag_0001

[OUTPUT]
    Name                file
    Match               tag_0001
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0002.log
    Parser              simple_parser
    DB                  /dbs/main
    Tag                 tag_0002

[OUTPUT]
    Name                file
    Match               tag_0002
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0003.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0003

[OUTPUT]
    Name                file
    Match               tag_0003
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0004.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0004

[OUTPUT]
    Name                file
    Match               tag_0004
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0005.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0005

[OUTPUT]
    Name                file
    Match               tag_0005
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0006.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0006

[OUTPUT]
    Name                file
    Match               tag_0006
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0007.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0007

[OUTPUT]
    Name                file
    Match               tag_0007
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0008.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0008

[OUTPUT]
    Name                file
    Match               tag_0008
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0009.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0009

[OUTPUT]
    Name                file
    Match               tag_0009
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0010.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0010

[OUTPUT]
    Name                file
    Match               tag_0010
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0011.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0011

[OUTPUT]
    Name                file
    Match               tag_0011
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0012.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0012

[OUTPUT]
    Name                file
    Match               tag_0012
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0013.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0013

[OUTPUT]
    Name                file
    Match               tag_0013
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0014.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0014

[OUTPUT]
    Name                file
    Match               tag_0014
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0015.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0015

[OUTPUT]
    Name                file
    Match               tag_0015
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0016.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0016

[OUTPUT]
    Name                file
    Match               tag_0016
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0017.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0017

[OUTPUT]
    Name                file
    Match               tag_0017
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0018.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0018

[OUTPUT]
    Name                file
    Match               tag_0018
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0019.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0019

[OUTPUT]
    Name                file
    Match               tag_0019
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0020.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0020

[OUTPUT]
    Name                file
    Match               tag_0020
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0021.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0021

[OUTPUT]
    Name                file
    Match               tag_0021
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0022.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0022

[OUTPUT]
    Name                file
    Match               tag_0022
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0023.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0023

[OUTPUT]
    Name                file
    Match               tag_0023
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0024.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0024

[OUTPUT]
    Name                file
    Match               tag_0024
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0025.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0025

[OUTPUT]
    Name                file
    Match               tag_0025
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0026.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0026

[OUTPUT]
    Name                file
    Match               tag_0026
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0027.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0027

[OUTPUT]
    Name                file
    Match               tag_0027
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0028.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0028

[OUTPUT]
    Name                file
    Match               tag_0028
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0029.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0029

[OUTPUT]
    Name                file
    Match               tag_0029
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0030.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0030

[OUTPUT]
    Name                file
    Match               tag_0030
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0031.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0031

[OUTPUT]
    Name                file
    Match               tag_0031
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0032.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0032

[OUTPUT]
    Name                file
    Match               tag_0032
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0033.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0033

[OUTPUT]
    Name                file
    Match               tag_0033
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0034.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0034

[OUTPUT]
    Name                file
    Match               tag_0034
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0035.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0035

[OUTPUT]
    Name                file
    Match               tag_0035
    Path                /logs/output

[INPUT]
    Name                tail
    Path                /logs/test/file_0036.log
    Parser              simple_parser
    DB                  /dbs/main   
    Tag                 tag_0036

[OUTPUT]
    Name                file
    Match               tag_0036
    Path                /logs/output
```

**Comment by edsiper** [comment]
assigned to @PettitWesley

**Comment by PettitWesley** [comment]
@etm42 I am confused... I do not see the cloudwatch output used in your config.

**Comment by PettitWesley** [comment]
Oh I see:

> The problem remains when switching from cloudwatch_logs OUTPUT plugin to file OUTPUT plugin (except the entries are duplicated to the same log and not to a different stream)

So its not a problem in cloudwatch, it is truly in tail.

**Comment by etm42** [comment]
Any news please? We're keen to have a fully working Fluent Bit, so that see see only valid entries in the CloudWatch streams. Correct, the issue does appear to be with tail.

**Comment by stawny** [comment]
Following the replication steps and extensively testing (using only `file` OUTPUT), I have made the following observations:

The number of INPUT streams has a direct relation to the number of duplicate entries. As long as fewer than 32 are used, I was not able to replicate any duplicated entries. When the number of streams is more than 32 (N-32 > 0), then we observe N-32*2 duplicates, namely the first and last N-32 tags. We also see a missing stream with odd numbers above 32. The following were tested:
```
N=34
tag_0001 - tag_0034 :
Duplicate entries found in:
2 tag_0001
2 tag_0034
Obervation:
first and last log receive duplicates

N=34
Removed tag_0026 and tag_0016
Duplicate entries found in:
2 tag_0001
2 tag_0034
Obervation:
first and last log receive duplicates (again)

N=33
Removed `tag_0002`,`tag_0009`,`tag_0034`
No duplicates observed, BUT:
tag_0033 is missing from output entirely

N=32
Removed `tag_0002`,`tag_0009`,`tag_0034`,`tag_0026`
No duplicates observed AND no missing logs

N=38
Added `tag_0037` and `tag_0038`
Duplicates:
      2 tag_0001
      2 tag_0002
      2 tag_0003
      2 tag_0004
      2 tag_0034
      2 tag_0035
      2 tag_0037
      2 tag_0038

N=37
Added `tag_0037`
Duplicates:
      2 tag_0001
      2 tag_0002
      2 tag_0003
      2 tag_0034
      2 tag_0035
      2 tag_0037
AND tag_0034 is missing.

N=24
Tags tag_0001 through tag_0024
No duplicates and no missing logs
```

**Comment by PettitWesley** [comment]
@edsiper this is a core issue. Something in routing must be broken when 32 or more inputs are configured. I am guessing the code has something hardcoded somewhere that adds this limitation.

**Comment by nokute78** [comment]
`flb_task_create` reports no route found when id=32.
It means this condition is not matched.
```c
        if ((((struct flb_input_chunk *) ic)->routes_mask & o_ins->mask_id) > 0) {
```

```
[2021/02/01 21:58:19] [debug] [task] created task=0x7f651406ce30 id=31 OK
[2021/02/01 21:58:19] [debug] [task] created task=0x7f651406cc60 id=32 without routes, dropping.
[2021/02/01 21:58:19] [debug] [task] destroy task=0x7f651406cc60 (task_id=32)
```

**Comment by nokute78** [comment]
Hmm, I sent a patch to mitigate this issue.
My patch allows 64 inputs. However this issue will happen when 64+ inputs...

**Comment by edsiper** [comment]
I've merged fix provided by @nokute78 on #2997. 

Now we are taking a look at PR #2914 which allow up to 256 outputs by default, but the value can be changed if needed to support more.

**Comment by etm42** [comment]
Thank you for issuing a fix.

I've tested this morning but we are still seeing the cross-stream duplication. To create our image I've cloned github.com/aws/aws-for-fluent-bit.git, then I've changed the line in Dockerfile that checks out Fluent-Bit as shown below:

```
[adstreamdev] lenny71 ./aws-for-fluent-bit > git diff HEAD~1 Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 53160cb..1aa3a72 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,12 @@
 FROM public.ecr.aws/amazonlinux/amazonlinux:latest as builder
 
-# Fluent Bit version; update these for each release
-ENV FLB_VERSION 1.6.10
+# Fluent Bit version; update these for each release:
+# Here, incremented from 1.6.10 to to 1.6.10.1 which doesn't exist externally.
+ENV FLB_VERSION 1.6.10.1
+
+# FluentBit commit ID for the fix here, https://github.com/fluent/fluent-bit/pull/2997
+ENV FLB_COMMIT_ID d8412da6c25212b4a8b6b170c8f32b5577f49cdb
+
 # branch to pull parsers from in github.com/fluent/fluent-bit-docker-image
 ENV FLB_DOCKER_BRANCH 1.6
 
@@ -37,7 +42,7 @@ RUN yum install -y  \
 WORKDIR /tmp/fluent-bit-$FLB_VERSION/
 RUN git clone https://github.com/fluent/fluent-bit.git /tmp/fluent-bit-$FLB_VERSION/
 WORKDIR /tmp/fluent-bit-$FLB_VERSION/build/
-RUN git fetch --all --tags && git checkout tags/v${FLB_VERSION} -b v${FLB_VERSION} && git describe --tags
+RUN git fetch --all --tags && git checkout ${FLB_COMMIT_ID} -b v${FLB_VERSION} && git describe --tags
 RUN cmake -DFLB_DEBUG=On \
           -DFLB_TRACE=Off \
           -DFLB_JEMALLOC=On \
```
This checks out the commit that should solve the issue before proceeding with the standard AWS for Fluent-Bit build. I've also ran this with some extra debug at this point and can confirm the first entry from `git log` is as below:

```
commit d8412da6c25212b4a8b6b170c8f32b5577f49cdb
Author: Takahiro Yamashita <nokute78@gmail.com>
Date:   Tue Feb 2 01:05:33 2021 +0900

    output: change maskid type to prevent integer overflow (#2997)

    Signed-off-by: Takahiro YAMASHITA <nokute78
```

Then, when I run new new container and send through some test messages, I see some of them in multiple streams.

Please can you confirm if I am following the correct logic to implement your fix?

Kind Regards,
Edd

**Comment by edsiper** [comment]
@etm42 can you try our rc4 ? the image is ```fluent/fluent-bit:1.7.0-rc4```.

**Comment by etm42** [comment]
@edsiper Thank you. That works from the AWS for Fluent-Bit docker image when performing the simple test. I will test in UAT on Monday.

**Comment by etm42** [comment]
@edsiper Confirmation, that's working now in UAT!

**Comment by matt-simons** [comment]
> I've merged fix provided by @nokute78 on #2997.
> 
> Now we are taking a look at PR #2882 which allow up to 256 outputs by default, but the value can be changed if needed to support more.

@edsiper is this user configurable or does it require a PR to raise the limit again? We've recently run into this limitation.

**Comment by edsiper** [comment]
@matt-simons it's fixed

**Comment by anuragmahanto** [comment]
@edsiper  can you please tell, In which fluent-bit release this fix will be included.
as I am not seeing the any release number under "milestone".

This is issue I am able to reproduce in 1.8.10 version.
