### ISSUE TITLE
Error io after upgrading to fluent-bit 1.7.0 from 1.6.10: [filter:kubernetes:kubernetes.0] upstream connection error

### ISSUE THREAD

**Issue by sondinhnwv** [fluent/fluent-bit#3077]
## Bug Report

We're seeing the same issue as https://github.com/fluent/fluent-bit/issues/2829 when upgrading to 1.7.0.

I can see that the commits that fixed the 1.6.x releases haven't been applied to 1.7.0, so that may be the issue.

The relevant commits fixing it in 1.6.8 were:

https://github.com/fluent/fluent-bit/commit/33be5a4d501d2c5f7501ea6e8e94bece1e3a533d
https://github.com/fluent/fluent-bit/commit/03daeebce0f0da56fb544372007c5f0842a4b818

The same configuration works in our previously running version of 1.6.10.

**Describe the bug**
Receiving `[2021/02/15 13:41:28] [error] [filter:kubernetes:kubernetes.0] upstream connection error` on kubernetes filter.

**Expected behavior**
Expected connect to be successful.

**Your Environment**
* Configuration: Fluentbit version 1.7.0
* Filters and plugins: Kubernetes

**Comment by edsiper** [comment]
## Resolution

#### root cause

Our container images tagged as ```1.7``` and ```1.7-debug``` had missing TLS certificates in the distroless layers.

#### solution

the container images from Docker hub has been corrected and now are fully functional.

**Comment by sondinhnwv** [comment]
Thanks it works for me now. Sorry for the wrong assumption in the bug report.

**Comment by sondinhnwv** [comment]
Sorry, disregard my previous message.

We're still getting the same error and I don't think adding TLS certs would fix it as Kubernetes has its own CA cert that should be used at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`.

Is there anything I can do to help debug?

**Comment by pschulten** [comment]
I have the same issue as @sondinhnwv  and getting the error when switching from 1.6 to 1.7. @edsiper, do you need more context?

**Comment by edsiper** [comment]
If the issue is reproducible with v1.7.1 in your environment let's join a call to troubleshoot. Let me know...

**Comment by pschulten** [comment]
Gladly. Today? 20:30 GMT+1?

**Comment by pschulten** [comment]
It's related to the tls change. Tried to set `tls.vhost` as suggested here: https://github.com/fluent/fluent-bit/issues/1615#issuecomment-602987226

circumvented it by ignoring tls verification with `tls.verify          Off`

running `openssl s_client -connect kubernetes.default.svc:443 -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt` in the fluent-bit pod works fine, though

**Comment by sondinhnwv** [comment]
/cc @edsiper

I've done a little more debugging and I think the problem is that partial chain checking is not set.

# Scenario 1

```openssl s_client -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -connect kubernetes.default.svc:443```

for me gives

```Verify return code: 2 (unable to get issuer certificate)```

# Scenario 2

```openssl s_client -CAfile /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -partial_chain -connect kubernetes.default.svc:443```

for me gives

```Verify return code: 0 (ok)```


I've done a little digging around and it looks curl sets [partial chain flag](https://github.com/curl/curl/blob/67d3afa73f4cdb8a6c473f911c8af800121e0a49/lib/vtls/openssl.c#L3049-L3074) which is why curling the https endpoint with the CA file works for me.

We don't have a self-signed CA, but an intermediate one instead, which explains it.

Is it possible to set `X509_V_FLAG_PARTIAL_CHAIN` to match curl's behaviour?

Also, can this issue be reopened?

**Comment by sondinhnwv** [comment]
For now we'll turn off tls.verify too.

**Comment by edsiper** [comment]
@sondinhnwv can you open a new ticket please asking for X509_V_FLAG_PARTIAL_CHAIN support ?

**Comment by AlaaAttya** [comment]
I'm still facing the same issue. I'm using this image https://hub.docker.com/layers/fluent/fluent-bit/1.7.4/images/sha256-a5db7a6c8360795bae658c6a08bbacdef24ecdecdb8edb44a691b17861de4a58?context=explore

and here's a sample of the configs i use

```
[FILTER]
      Name                kubernetes
      Match               kube.*
      Kube_URL            https://kubernetes.default.svc:443
      Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
      Kube_Tag_Prefix     kube.var.log.containers.
      Merge_Log           On
      Merge_Log_Key       log_processed
      K8S-Logging.Parser  On
      K8S-Logging.Exclude On
      Annotations         On
      Merge_Log_Trim      On
      Use_Kubelet         On
      tls.verify          Off
```

**Comment by wtchangdm** [comment]
@AlaaAttya I am facing this is with 1.7.3 & 1.7.4 as well, did you notice any unusual errors? I only saw a bunch of `kubelet upstream connection error`.

I also tried to use kubelet instead kube-apiserver for metadata, but this issue still persists.

**Comment by stevehipwell** [comment]
I'm seeing this in a Kind cluster with Fluent Bit v1.8.1.

https://github.com/fluent/helm-charts/runs/3075290266?check_suite_focus=true#step:9:178

**Comment by stevehipwell** [comment]
And now I feel stupid for forgetting to set `hostNetwork: true`  & `dnsPolicy: ClusterFirstWithHostNet`.

**Comment by awcheney** [comment]
Hey folks - I'm seeing this with image: kubesphere/fluent-bit:v1.8.3. Fluentbit pod logs contain lots of:
`[2021/09/14 17:33:09] [error] [filter:kubernetes:kubernetes.2] kubelet upstream connection error`
