### ISSUE TITLE
Fluent Bit failed to start correctly under the multithreading mode on Windows

### ISSUE THREAD

**Issue by qingling128** [fluent/fluent-bit#3646]
## Bug Report

**Describe the bug**
We added `workers 8` in the `stackdriver` output plugin config to enable multithreading. This worked well on Linux, but not on Windows.

Sample config section:
```
[OUTPUT]
    # https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver
    Name              stackdriver
    resource          gce_instance
    stackdriver_agent Google-Cloud-Ops-Agent-Logging/latest (BuildDistro=build_distro;Platform=windows;ShortName=win_platform;ShortVersion=win_platform_version)
    workers           8
    Match_Regex       ^(windows_event_log)$

    # https://docs.fluentbit.io/manual/administration/scheduling-and-retries
    # After 3 retries, a given chunk will be discarded. So bad entries don't accidentally stay around forever.
    Retry_Limit  3

    # https://docs.fluentbit.io/manual/administration/security
    # Enable TLS support.
    tls         On
    # Do not force certificate validation.
    tls.verify  Off
```

**Errors in the log**
Sample log snippets:

```
[2021/06/11 08:06:09] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:09] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:09] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:09] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:09] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:09] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:09] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:09] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:09] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:09] [ info] [sp] stream processor started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:09] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:14] [ info] [engine] started (pid=4228)
[2021/06/11 08:06:14] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:14] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:14] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:14] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:14] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:14] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:14] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:14] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:14] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:14] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:14] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:14] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:14] [ info] [sp] stream processor started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:14] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:18] [ info] [engine] started (pid=1524)
[2021/06/11 08:06:18] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:18] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:18] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:18] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:18] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:18] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:18] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:18] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:18] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:18] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:18] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:18] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:18] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:18] [ info] [sp] stream processor started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:18] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:19] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:460-1623398769.756208000.flb
[2021/06/11 08:06:19] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:4228-1623398774.659223500.flb
[2021/06/11 08:06:22] [ info] [engine] started (pid=540)
[2021/06/11 08:06:22] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:22] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:22] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:22] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:22] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:22] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:22] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:22] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:22] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:22] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:22] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:22] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:22] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:22] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:22] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:22] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:22] [ info] [sp] stream processor started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:22] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:26] [ info] [engine] started (pid=5100)
[2021/06/11 08:06:26] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:26] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:26] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:26] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:26] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:26] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:26] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:26] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:26] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:26] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:26] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:26] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:26] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/540-1623398782.291411600.flb
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:26] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:26] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:26] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:26] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:26] [ info] [sp] stream processor started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:26] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:27] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:1524-1623398778.426215300.flb
[2021/06/11 08:06:27] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:4228-1623398774.659223500.flb
[2021/06/11 08:06:27] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:460-1623398769.756208000.flb
[2021/06/11 08:06:27] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:540-1623398782.291411600.flb
[2021/06/11 08:06:29] [ info] [engine] started (pid=392)
[2021/06/11 08:06:29] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:29] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:29] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:29] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:29] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:29] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:29] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:29] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/5100-1623398786.156666900.flb
[2021/06/11 08:06:29] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/540-1623398782.291411600.flb
[2021/06/11 08:06:29] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:29] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:29] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:29] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:30] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:29] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:29] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:29] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:30] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:30] [ info] [sp] stream processor started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:30] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:31] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:1524-1623398778.426215300.flb
[2021/06/11 08:06:31] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:4228-1623398774.659223500.flb
[2021/06/11 08:06:31] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:460-1623398769.756208000.flb
[2021/06/11 08:06:31] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:5100-1623398786.156666900.flb
[2021/06/11 08:06:31] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:540-1623398782.291411600.flb
[2021/06/11 08:06:33] [ info] [engine] started (pid=3192)
[2021/06/11 08:06:33] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:33] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:33] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:33] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:33] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:33] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:33] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:33] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/392-1623398790.26899700.flb
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/5100-1623398786.156666900.flb
[2021/06/11 08:06:33] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/540-1623398782.291411600.flb
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:33] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:33] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:33] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:33] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:33] [ info] [sp] stream processor started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:33] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:38] [ info] [engine] started (pid=1208)
[2021/06/11 08:06:38] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:38] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:38] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:38] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:38] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:38] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:38] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:38] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/3192-1623398793.855174800.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/392-1623398790.26899700.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/5100-1623398786.156666900.flb
[2021/06/11 08:06:38] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/540-1623398782.291411600.flb
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:38] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/06/11 08:06:38] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/06/11 08:06:38] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/06/11 08:06:38] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/06/11 08:06:38] [ info] [sp] stream processor started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/06/11 08:06:38] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:1524-1623398778.426215300.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:3192-1623398793.855174800.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:392-1623398790.26899700.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:4228-1623398774.659223500.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:460-1623398769.756208000.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:5100-1623398786.156666900.flb
[2021/06/11 08:06:39] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:540-1623398782.291411600.flb
[2021/06/11 08:06:42] [ info] [engine] started (pid=444)
[2021/06/11 08:06:42] [error] [storage] [cio file] hash does not match (2891792118 != 1104745215)
[2021/06/11 08:06:42] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/1524-1623398779.492465100.flb' (cio_file_open() line=386)
[2021/06/11 08:06:42] [error] [storage] [cio file] hash does not match (2510510237 != 1104745215)
[2021/06/11 08:06:42] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/460-1623398771.989506800.flb' (cio_file_open() line=386)
[2021/06/11 08:06:42] [ info] [storage] version=1.1.1, initializing...
[2021/06/11 08:06:42] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/06/11 08:06:42] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/06/11 08:06:42] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1208-1623398798.233756400.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1524-1623398778.426215300.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/3192-1623398793.855174800.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/392-1623398790.26899700.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/4228-1623398774.659223500.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/460-1623398769.756208000.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/5100-1623398786.156666900.flb
[2021/06/11 08:06:42] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/540-1623398782.291411600.flb
```

[full log.txt](https://github.com/fluent/fluent-bit/files/6657570/full.log.txt)

**Environment**
* Version used: Fluent Bit 1.7.8
* Operating System and version: Windows 2019
* Full configs:
   * Linux: https://github.com/GoogleCloudPlatform/ops-agent/blob/ab1eb82341df5d39d1a0287f6f7d39b2e329e77c/confgenerator/testdata/valid/linux/default_config/golden_fluent_bit_main.conf
   * Windows: https://github.com/GoogleCloudPlatform/ops-agent/blob/ab1eb82341df5d39d1a0287f6f7d39b2e329e77c/confgenerator/testdata/valid/windows/default_config/golden_fluent_bit_main.conf

**Comment by qingling128** [comment]
This was fixed in `1.7.9`.

**Comment by jkschulz** [comment]
After some more tests with `1.7.9` (still using `workers 8` in the output config), it turns out it's not fixed yet. I've run our tests twice, but I only saw these issues on one of the runs, so it might not be deterministic. Will run a couple more times to see what happens.

### Environment
- Version: Fluent Bit v1.7.9
- OS: Windows Server 2019 (Google Compute Engine image: `windows-2019-core`)
- Config: https://github.com/GoogleCloudPlatform/ops-agent/blob/54217115272b13056c57145af44ff2b5059849b7/confgenerator/testdata/valid/windows/default_config/golden_fluent_bit_main.conf)
- Logs: [fluent_bit_agent_logs_2021_07_15.txt](https://github.com/fluent/fluent-bit/files/6850889/fluent_bit_agent_logs_2021_07_15.txt)

### Summary

Output plugin config:
```
[OUTPUT]
    # https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver
    Name              stackdriver
    resource          gce_instance
    stackdriver_agent Google-Cloud-Ops-Agent-Logging/2.0.2 (BuildDistro=windows-ltsc2019;Platform=windows;ShortName=Microsoft Windows Server 2019 Datacenter;ShortVersion=10.0.17763 Build 17763)
    workers           8
    Match_Regex       ^(windows_event_log)$

    # https://docs.fluentbit.io/manual/administration/scheduling-and-retries
    # After 3 retries, a given chunk will be discarded. So bad entries don't accidentally stay around forever.
    Retry_Limit  3

    # https://docs.fluentbit.io/manual/administration/security
    # Enable TLS support.
    tls         On
    # Do not force certificate validation.
    tls.verify  Off
```

Here are the logs before the first time it terminated unexpectedly:
```
[2021/07/15 20:43:43] [ info] [engine] started (pid=820)
[2021/07/15 20:43:43] [ info] [storage] version=1.1.1, initializing...
[2021/07/15 20:43:43] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/07/15 20:43:43] [ info] [storage] normal synchronization mode, checksum enabled, max_chunks_up=128
[2021/07/15 20:43:43] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/07/15 20:43:43] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/07/15 20:43:43] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/07/15 20:43:43] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/07/15 20:43:43] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/07/15 20:43:43] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/07/15 20:43:43] [ info] [sp] stream processor started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/07/15 20:43:43] [ info] [output:stackdriver:stackdriver.1] worker #6 started
```

As it restarted more and more times, these `cio file` errors snowballed. Not sure if it's a red herring, or if there's still a residual issue in the same vein as https://github.com/fluent/fluent-bit/issues/2889.  Example:
```
[2021/07/15 20:44:15] [ info] [engine] started (pid=2688)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (3101605480 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/2248-1626381828.113183700.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (2214285912 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/2320-1626381852.275309700.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (1748826427 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/3620-1626381840.427981300.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (2346783337 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/3932-1626381848.519721800.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (360112551 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'emitter.3/4296-1626381831.435065000.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (214559790 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'tail.0/2248-1626381828.117552100.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (3537780866 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'tail.0/2320-1626381852.273013800.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (1502629131 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'tail.0/3620-1626381840.650761700.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (3168280644 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'tail.0/3932-1626381848.406869400.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [error] [storage] [cio file] hash does not match (755355941 != 1104745215)
[2021/07/15 20:44:15] [error] [storage] [cio file] cannot verify checksum on 'tail.0/4296-1626381831.713579000.flb' (cio_file_open() line=386)
[2021/07/15 20:44:15] [ info] [storage] version=1.1.1, initializing...
```

**Comment by edsiper** [comment]
assigned to @leonardo-albertovich

**Comment by qingling128** [comment]
We are disabling `checksum` to isolate the issue to checksum as we are not sure if the error above is red herring or not. CC @jkschulz

**Comment by jkschulz** [comment]
Disabling `checksum` made many more of our tests pass, but I don't think for the right reasons -- it seems like the agent takes longer to die, but while it's running, it's able to make some progress.   

In 2 tries with `checksum off`, 
- tests that look for a log being written to Google Logging (with many retries) passed for all versions but 1 (the 1 failing version wasn't the same each time), whereas with `checksum on`, they fail for all but 1 (the 1 passing version wasn't the same each time)
- tests that look for a running `fluent-bit` process (with no retries) failed for all or all but 1 versions, which is ~the same as with `checksum off`. 

Nothing that different in the logs, minus the expected lack of `checksum`/`hash` errors:
- Full output: [fluent_bit_agent_logs_checksum_off.txt](https://github.com/fluent/fluent-bit/files/6880994/fluent_bit_agent_logs_checksum_off.txt)
```
2021/07/21 14:39:08 stdout: [2021/07/21 21:30:07] [ info] [engine] started (pid=1708)
[2021/07/21 21:30:07] [ info] [storage] version=1.1.1, initializing...
[2021/07/21 21:30:07] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/07/21 21:30:07] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/07/21 21:30:07] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/07/21 21:30:07] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/07/21 21:30:07] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/07/21 21:30:07] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/07/21 21:30:07] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/07/21 21:30:07] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/07/21 21:30:07] [ info] [sp] stream processor started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/07/21 21:30:07] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/07/21 21:30:09] [ info] [engine] started (pid=2564)
[2021/07/21 21:30:09] [ info] [storage] version=1.1.1, initializing...
[2021/07/21 21:30:09] [ info] [storage] root path 'C:\ProgramData\Google\Cloud Operations\Ops Agent\run\buffers'
[2021/07/21 21:30:09] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/07/21 21:30:09] [ info] [storage] backlog input plugin: storage_backlog.2
[2021/07/21 21:30:09] [ info] [input:storage_backlog:storage_backlog.2] queue memory limit: 47.7M
[2021/07/21 21:30:09] [ info] [input:storage_backlog:storage_backlog.2] register emitter.3/1708-1626903008.319627700.flb
[2021/07/21 21:30:09] [ info] [input:storage_backlog:storage_backlog.2] register tail.0/1708-1626903007.152524000.flb
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2021/07/21 21:30:09] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2021/07/21 21:30:09] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] metadata_server set to http://metadata.google.internal
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #4 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #5 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #6 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #7 started
[2021/07/21 21:30:09] [ warn] [output:stackdriver:stackdriver.1] client_email is not defined, using a default one
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #0 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #1 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #2 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.0] worker #3 started
[2021/07/21 21:30:09] [ warn] [output:stackdriver:stackdriver.1] private_key is not defined, fetching it from metadata server
[2021/07/21 21:30:09] [ info] [sp] stream processor started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #5 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #6 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #7 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #0 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #1 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #2 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #3 started
[2021/07/21 21:30:09] [ info] [output:stackdriver:stackdriver.1] worker #4 started
[2021/07/21 21:30:10] [ info] [input:storage_backlog:storage_backlog.2] queueing emitter.3:1708-1626903008.319627700.flb
[2021/07/21 21:30:10] [ info] [input:storage_backlog:storage_backlog.2] queueing tail.0:1708-1626903007.152524000.flb
```

**Comment by jkschulz** [comment]
Confirmed that https://github.com/fluent/fluent-bit/pull/3836 fixed this issue.
