### ISSUE TITLE
"cannot increase buffer" Kinesis Firehose output

### ISSUE THREAD

**Issue by ingshtrom** [fluent/fluent-bit#3900]
## Bug Report

**Describe the bug**
I get a lot of log messages stating that the http client cannot increase the buffer size. I've only started seeing this in version `1.8.2` (and I presume all `1.8.x`) since I believe #3339 was introduced in one of the releases `1.8.(0|1|2)`. I'm concerned that this is causing issues, although as far as I can tell logs are being sent correctly. In my tests we are using 2 vCPUs on a `t3.xlarge` EC2 instance in AWS, which seems very high for sending 2500 records per second to Kinesis Firehose.

~~I should also note, from what I can tell we don't use the default `flb_http_client` for the Kinesis Firehose connections, so we are only using it in `flb_aws_util`, which is only doing authentication from what I can tell.~~

~~I started working on fixing this by allowing configuration of each AWS plugin which utilizes the `flb_aws_util` code for authentication, but if it's only authentication, we could probably just hard-code a good value and call it a day, right? Those responses shouldn't change in size so there is no reason to need to tune those values, unless I'm missing something.~~

[edit]: I realized that the `flb_aws_util.c`'s method `request_do` is actually a wrapper for all AWS plugins to make requests to the AWS API, thus each output plugin needs to have a configuration for the buffer size. I am going to start by adding a configuration parameter to each AWS output plugin which uses this method for a parameter `size_t http_client_buffer_size;`. This should allow configuration of this parameter and help with the issue. I'll open a PR once I've got it working and tested in my environment.

cc @PettitWesley 

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2021/08/02 16:50:43] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:43] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:43] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:44] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:44] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:44] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
[2021/08/02 16:50:44] [ warn] [http_client] cannot increase buffer: current=4096 requested=36864 max=4096
```
- Steps to reproduce the problem:

Run fluent-bit with the `kinesis_firehose` output plugin. I presume it always happens, but I'm load testing with a [test repo I created](https://github.com/ingshtrom/fluent-bit-kinesis-test) for the purpose. Make sure Fluent Bit is upgraded to `1.8.2` Docker image tag and you should see the message after running for a minute.

**Expected behavior**
This message should not occur with default parameter installations, but for pipelines which need more tuning, we should provide a parameter to tune this.

**Screenshots**
To get an idea of the scale of the tests I'm running
![image](https://user-images.githubusercontent.com/571756/127897622-6280ca96-6296-4dd1-888e-802a70813d06.png)

**Your Environment**

* Version used: 1.8.2
* Configuration: See [here](https://github.com/ingshtrom/fluent-bit-kinesis-test/blob/main/fluent-bit.conf)
* Environment name and version (e.g. Kubernetes? What version?): Running in Docker Compose, similar to [this example from the docs](https://docs.fluentbit.io/manual/local-testing/logging-pipeline))
* Server type and version: Docker Image `fluent/fluent-bit:1.8.2`
* Operating System and version: distroless
* Filters and plugins: `in_tail`, `out_kinesis_firehose`

**Additional context**

**Comment by ingshtrom** [comment]
To get to a working solution quicker, I opted to hard-code a value of `36864` for the `http_client` buffer size...I need more I guess 🙄 
```
fluent-bit    | [2021/08/02 17:33:42] [ warn] [http_client] cannot increase buffer: current=36864 requested=69632 max=36864
fluent-bit    | [2021/08/02 17:33:42] [ warn] [http_client] cannot increase buffer: current=36864 requested=69632 max=36864
fluent-bit    | [2021/08/02 17:33:42] [ warn] [http_client] cannot increase buffer: current=36864 requested=69632 max=36864
fluent-bit    | [2021/08/02 17:33:42] [ warn] [http_client] cannot increase buffer: current=36864 requested=69632 max=36864
fluent-bit    | [2021/08/02 17:33:42] [ warn] [http_client] cannot increase buffer: current=36864 requested=69632 max=36864
```

I guess I'll just make the change to support configuring this so I can iterate quicker.

**Comment by PettitWesley** [comment]
@edsiper

**Comment by nokute78** [comment]
#3339 is to enrich log. It means the issue becomes obvious by the patch.  I think it is not a root cause.

By the way,  I wonder about below codes.
https://github.com/fluent/fluent-bit/blob/2754cd86d137530009b49894ff6359fa6b05cb4e/src/flb_http_client.c#L824-L833

In this case, the values are below.
I think we need to increase `resp.data_size_max` first and it should be grater than `new_size`. Hmm.
|Name|Value|Log|
|---|----|--|
|resp.data_size_max|4096|`max=4096`|
|new_size|36864 -> 4096 (L827) |`requested=36864`|
|resp.data_size|4096|`current=4096`|

**Comment by PettitWesley** [comment]
@nokute78 Yeah I agree this code logic looks incorrect.

**Comment by ingshtrom** [comment]
@nokute78 right, I totally agree. Sorry I wasn't explicit, there. My concern was that _something_ was off, since that log message indicates such, but it was above my head as to what exactly was wrong. 

FWIW, I did create [a patch](https://github.com/fluent/fluent-bit/compare/master...ingshtrom:fix-http-buffer-size-aws) to allow modifying the http_client buffer size based on my initial thoughts prior to you both commenting. It didn't seem to have any effect, except it took longer for Fluent Bit to be running prior to me receiving the message "cannot increase buffer".

I even pushed it all the way to 500KB just as an experiment and after it was running for a bit Fluent Bit crashed
```
[2021/08/02 19:09:49] [ warn] [http_client] cannot increase buffer: current=500000 requested=532768 max=500000
[2021/08/02 19:09:49] [ warn] [http_client] cannot increase buffer: current=500000 requested=532768 max=500000
[2021/08/02 19:09:49] [ info] [output:kinesis_firehose:kinesis_firehose.1] Processed 3928 records, sent 3928 to test-alexh-haproxy-access-logs
[2021/08/02 19:09:50] [ info] [output:kinesis_firehose:kinesis_firehose.1] Processed 4679 records, sent 4679 to test-alexh-haproxy-access-logs
[2021/08/02 19:09:50] [ warn] [http_client] cannot increase buffer: current=500000 requested=532768 max=500000
[2021/08/02 19:09:50] [ warn] [output:kinesis_firehose:kinesis_firehose.1] unhandled event type => 72680198
[2021/08/02 19:09:50] [ warn] [output:kinesis_firehose:kinesis_firehose.1] unhandled event type => 72680198
[2021/08/02 19:09:50] [ warn] [output:kinesis_firehose:kinesis_firehose.1] unhandled event type => 72680198
[2021/08/02 19:09:50] [ warn] [output:kinesis_firehose:kinesis_firehose.1] unhandled event type => 72680198
```

I feel out of my wheelhouse at this point (and frankly I've never written any C). Let me know how I can help and test things out!

**Comment by pranavmarla** [comment]
bump

**Comment by PettitWesley** [comment]
I think this will fix it: https://github.com/fluent/fluent-bit/pull/4047

**Comment by PettitWesley** [comment]
This has been fixed in 1.8.8

**Comment by PettitWesley** [comment]
Sorry, I meant 1.8.7

**Comment by brsolomon-deloitte** [comment]
> Sorry, I meant 1.8.7

@PettitWesley still seeing this in 1.8.13, can you point to the relevant commit in 1.8.7?

> [2022/03/09 18:19:11] [ warn] [http_client] cannot increase buffer: current=32000 requested=64768 max=32000

**Comment by PettitWesley** [comment]
@brsolomon-deloitte https://github.com/fluent/fluent-bit/pull/4048
