### ISSUE TITLE
Fluentbit stops processing (tail input / graylog output)

### ISSUE THREAD

**Issue by jamesjhhan** [fluent/fluent-bit#4376]
## Bug Report

**Describe the bug**
In short, at some point in time eventually, fluentbit hangs and quits sending to graylog from a tail input file.  The logs even at trace level doesnt reveal anything useful.  Also, to make matters worse, the fluentbit monitoring endpoint responds fine so our alerting system cant even detect when it's stopped working when it hits the fluentbit monitoring endpoint. 

**To Reproduce**
- Steps to reproduce the problem:
1. Start fluentbit windows service (sc start fb)
2. Fluentbit sends log entries to fluentbit without issue
3. After some random time (usually after at least a few hours.. could be days), it inexplicably stops.
 
**Expected behavior**
To keep forwarding to Graylog

**Screenshots**
n/a

**Your Environment**

* Version used: Fluentbit 1.8.10

* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):  No container.  Just running as a simple windows service.
* Operating System and version: Windows Server 2012 R2
* Filters and plugins: None

**Additional context**
I can circumvent by killing the process (trying to stop the service when its in this hung state does not stop the service) and restarting but obviously this isn't a solution nor the best mitigation strategy. This is a showstopper issue.  Any help would be really appreciated.

UPDATE: After evaluating the logs, it seems on some of our servers, there could have been issues at some point in its lifetime sending to Graylog (unreachable due to load on graylog, etc) but it definitely had access by the time I ended up killing and restarting the service so maybe it is a variable in fluentbit going to sleep forever.  I am wondering if this issue is related.. https://github.com/fluent/fluent-bit/issues/4373

Fluentbit Config:
[SERVICE]
    # Flush
    # =====
    # set an interval of seconds before to flush records to a destination
    flush        2

    # Grace
    # Wait time (seconds) on exit
    grace        1

    # Daemon
    # ======
    # instruct Fluent Bit to run in foreground or background mode.
    daemon       Off

    # Log_Level
    # =========
    # Set the verbosity level of the service, values can be:
    #
    # - error
    # - warning
    # - info
    # - debug
    # - trace
    #
    # by default 'info' is set, that means it includes 'error' and 'warning'.
    log_level    info
    log_file     D:\Logs\Fluentbit\fblog.txt

    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf

    # Plugins File
    # ============
    # specify an optional 'Plugins' configuration file to load external plugins.
    plugins_file plugins.conf

    # HTTP Server
    # ===========
    # Enable/Disable the built-in HTTP Server for metrics
    http_server  on
    http_listen  0.0.0.0
    http_port    2020

    # Storage
    # =======
    # Fluent Bit can use memory and filesystem buffering based mechanisms
    #
    # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
    #
    # storage metrics
    # ---------------
    # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
    # exported only if the 'http_server' option is enabled.

    storage.metrics on

    # storage.path
    # ------------
    # absolute file system path to store filesystem data buffers (chunks).

    storage.path D:\Logs\Fluentbit

    # storage.sync
    # ------------
    # configure the synchronization mode used to store the data into the
    # filesystem. It can take the values normal or full.

    storage.sync full

    # storage.checksum
    # ----------------
    # enable the data integrity check when writing and reading data from the
    # filesystem. The storage layer uses the CRC32 algorithm.

    storage.checksum on

    # storage.backlog.mem_limit
    # -------------------------
    # if storage.path is set, Fluent Bit will look for data chunks that were
    # not delivered and are still in the storage layer, these are called
    # backlog data. This option configure a hint of maximum value of memory
    # to use when processing these records.

    storage.backlog.mem_limit 100M

[INPUT]
    Name tail
    parser gelf
    Path D:\Logs\app\log-*.txt
    Exclude_Path D:\Logs\app\archive
    DB D:\Logs\app\logdb.db
    DB.locking true
    DB.sync full
    Refresh_Interval 30
    Read_from_Head true
    Skip_Long_Lines On
    Buffer_Max_Size 1MB
    Mem_Buf_Limit 100MB
    Buffer_Chunk_Size 1MB
    storage.type filesystem

[OUTPUT]
    name  gelf
    match *
    host graylog.mylocalserver
    port 12201
    mode tls
    Gelf_Short_Message_Key short_message
    Gelf_Full_Message_Key @m
    Gelf_Timestamp_Key @t
    Retry_Limit false
    tls on
    tls.verify off

Here is the last few entries from the log (once it's in the hung state, there are no entries written out to the log)....
[2021/11/26 09:29:59] [debug] [task] created task=00000083DBD66890 id=0 OK
[2021/11/26 09:29:59] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 is now available
[2021/11/26 09:29:59] [debug] [out coro] cb_destroy coro_id=5201
[2021/11/26 09:29:59] [debug] [task] destroy task=00000083DBD66890 (task_id=0)
[2021/11/26 09:30:03] [debug] [storage] [cio file] synced at: tail.0/8460-1637937001.890037000.flb
[2021/11/26 09:30:03] [debug] [task] created task=00000083DBD66800 id=0 OK
[2021/11/26 09:30:03] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 has been assigned (recycled)
[2021/11/26 09:30:03] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 is now available
[2021/11/26 09:30:03] [debug] [out coro] cb_destroy coro_id=5202
[2021/11/26 09:30:03] [debug] [task] destroy task=00000083DBD66800 (task_id=0)
[2021/11/26 09:30:05] [debug] [storage] [cio file] synced at: tail.0/8460-1637937004.898131600.flb
[2021/11/26 09:30:05] [debug] [task] created task=00000083DBD65330 id=0 OK
[2021/11/26 09:30:05] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 has been assigned (recycled)
[2021/11/26 09:30:05] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 is now available
[2021/11/26 09:30:05] [debug] [out coro] cb_destroy coro_id=5203
[2021/11/26 09:30:05] [debug] [task] destroy task=00000083DBD65330 (task_id=0)
[2021/11/26 09:30:15] [debug] [storage] [cio file] synced at: tail.0/8460-1637937014.402296500.flb
[2021/11/26 09:30:15] [debug] [task] created task=00000083DBD65450 id=0 OK
[2021/11/26 09:30:15] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 has been assigned (recycled)
[2021/11/26 09:30:15] [debug] [upstream] KA connection #832 to graylog.mylocalserver:12201 is now available
[2021/11/26 09:30:15] [debug] [out coro] cb_destroy coro_id=5204
[2021/11/26 09:30:15] [debug] [task] destroy task=00000083DBD65450 (task_id=0)
[2021/11/26 09:30:21] [debug] [input:tail:tail.0] 0 new files found on path 'D:\Logs\app\log-*.txt'
[2021/11/26 09:30:45] [debug] [upstream] drop keepalive connection #-1 to graylog.mylocalserver:12201 (keepalive idle timeout)
[2021/11/26 09:30:45] [debug] [storage] [cio file] synced at: tail.0/8460-1637937045.394740500.flb
[2021/11/26 09:30:45] [debug] [task] created task=00000083DBD65720 id=0 OK

**Comment by jamesjhhan** [comment]
This commit looks promising.. https://github.com/fluent/fluent-bit/commit/ac5d89f99fa87d1d84d573f62ddf9cd6634bdf79

**Comment by edsiper** [comment]
Fixed in #4411

**Comment by jamesjhhan** [comment]
Unfortunately, this issue is not fixed.  Using memory storage type has made things less recurring but it still happens often enough where its not reliable.  Only mitigation is to keep restarting fluentbit every so often.  :-(  Can this issue be reopened?

**Comment by singlesparkgreatfire** [comment]
Hi @jamesjhhan , I think we met the exact same issue, OS is windows 2016, kind of random log forward stuck after a random period, could be from 2hours - 2 days. Is there any progress about this issue?

**Comment by Jonathan-w6d** [comment]
Same issue, at some random point logs stop being forwarded to Opensearch.
I use the exact same conf in prod and dev environments, it only happens to the dev environment.

**Comment by ThanasisBarekas** [comment]
Hello,
Why this issue is closed since it is not fixed ?
