### ISSUE TITLE
Fluent-bit in K8s stops sending logs to elastic after a few hours

### ISSUE THREAD

**Issue by marckamerbeek** [fluent/fluent-bit#649]
Fluentbit stops sending logs to Elasticsearch after several hours without telling me why. Fluent-bit docker is not crashing. It just stops doing what it shoud do.  What could be the reason? I can't figure out why. It happens in every of the 3 cluster.

Situation: 3x (14 nodes k8s cluster (including 3 masters))
Version fluent-bit: 0.13.3
Kubernetes version: 1.8.4
Node OS: Red Hat 7.4 Maipo

Resource limits k8s:
`"resources": {
  "limits": {
    "cpu": "100m",
    "memory": "1Gi"
  },
  "requests": {
    "cpu": "100m",
    "memory": "512Mi"
  }
}`

Configuration:

[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug

[INPUT]
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size 25MB
    DB /var/log/containers/fluent-bit.db
    Exclude_Path *kube-system*.log
    Mem_Buf_Limit 25MB
    Name tail
    Parser json
    Path /var/log/containers/*.log
    Refresh_Interval 5
    Skip_Long_Lines On
    Tag kube.services.*

[FILTER]
    K8S-Logging.Parser On
    K8S-Logging.exclude True
    Kube_URL https://${KUBERNETES_SERVICE_HOST}:443
    Match kube.*
    Merge_JSON_Log On
    Name kubernetes
    tls.verify Off
	
[PARSER]
    Decode_Field_As escaped log
    Format json
    Name json
    Time_Format %Y-%m-%dT%H:%M:%S %z
    Time_Key time

[OUTPUT]
    Host xxx.xxx.xxx.xxx
    Include_Tag_Key true
    Logstash_DateFormat %G.%V
    Logstash_Format On
    Logstash_Prefix k8s-services-tst
    Match kube.services.*
    Name es
    Port 9200
    Retry_Limit False

**Comment by MohdAhmad** [comment]
@marckamerbeek have you checked the logs from fluent-bit and elastisearch?

**Comment by marckamerbeek** [comment]
Yes...nothing in the logs. Nothing in elastic. Start building my own fluentbit with extra debug logging. See if that shows some light.

**Comment by jpbelanger-mtl** [comment]
@marckamerbeek thanks for the update. We might just rollback to the previous release we were running (0.12.11). It was using a insane amount of memory but at least it was sending log and restarting by itself when it reached kube memory limit. Wonder why not more people are having that same problem.

**Comment by marckamerbeek** [comment]
Thats not an option for me since version 0.13.x contains some critical functionality for kubernetes plugin. @edsiper Could you please shine a ligth on this problem. I have no clue where to start. I'm able to do some work on fluent-bit now and build my own release. But my C skills are still not that good (but learning...:-))

**Comment by edsiper** [comment]
would you please provide some metrics snapshots using Prometheus ?, meaning: when you don't see any messages ingested into elasticsearch, how Fluent Bit metrics looks like ?

**Comment by marckamerbeek** [comment]
We use Prometheus in our cluster although not in combination with fluent-bit. I was not aware of that possibility. I'll will instrument fluent-bit right away with prometheus. Give me sec...

**Comment by marckamerbeek** [comment]
This is the fluent-bit data in Grafana:
![image](https://user-images.githubusercontent.com/7521474/42819022-9f861718-89d2-11e8-8841-648cc34baa6b.png)

**Comment by edsiper** [comment]
I see a high number of retries, which could mean problems reaching
elaetocsearch or elaetocsearch errors. Do u see any anomally in elastic
logs?

**Comment by marckamerbeek** [comment]
The last time I looked I saw some parsing errors, but I got rid of 90% I think. I'll check it again. I'll need to wait to get access again to the Elastic Cluster. I'll come back on this.

**Comment by seeruk** [comment]
This sounds very similar to an issue I'm currently experiencing with fluent-bit 0.14.7.

We're running in AWS, on Elastic Beanstalk (shudder), starting up a fluent-bit container alongside our apps, and using it as a Docker logging driver. It works for most of the day, then suddenly around the same time each day, not even when it's really any more busy than usual, it just completely stops logging.

We send our logs to AWS Elasticsearch currently, and so do many of our other applications, yet there is only one application that is having problems, and we have other applications that are noisier than this application that has stopped logging occasionally.

One potential reason I've seen is the Docker log rotation. The first log file I see contains 0 errors. 6 lines into starting a new log file, I start seeing this error:

```
[2018/11/21 18:19:32] [  Error] timerfd_settime: Invalid argument, errno=22 at /tmp/fluent-bit-0.14.7/lib/monkey/mk_core/mk_event_epoll.c:190
```

This happens continuously from the point where the log rotates, until the instance is rebooted / terminated. I'm a little bit tempted at the moment to explore how to use fluentd instead, but the reason we moved from fluentd to fluent-bit was because of fluentd's slow startup time causing issues with Elasticbeanstalk starting our apps (i.e. Docker complains the logging driver is not ready and the app just reboots continuously).

**Comment by mgsh** [comment]
we have a similar issue where fluent-bit stops tracking a few applications after a few hours. we use fluent-bit in eks, to push logs to stackdriver. on further investigation this is what i found out.

our setup (fluent-bit configs attached):
- fluent-bit is set up to tail all files matching `/var/log/conainers/*.log`. kubernetes takes care of setting up symlinks in `/var/log/containers/` and logs in `/var/lib/docker/containers/` (through `/var/log/pods/`)
- by default, aws eks sets up docker with this `log-opts` setting `{"max-size":"10m","max-file":"10"}` (in `/etc/docker/daemon.json`)

issues:
1. **gaps in container logs**: when logs for a container rotates too fast (either for fluent-bit to keep up or for kubernetes to update symlinks), fluent-bit is still tailing one of the rotated files (*.{1..9}). by the time fluent-bit gets around to use the current log file symlink for that container in `/var/log/containers/`, some rotated files in between are never tailed (because `/var/log/containers` only has symlinks pointing to the current log file for each container). i think this can also be confirmed by examining the sqlite db, where it keeps a rotated flag for every log file. in cases where the rotated file is .2 or higher, i think logs in between were missed.
2. **container logs stop after few hours**: when i inspected the file handles held by fluent-bit for a container where it stopped tailing after a few hours, i noticed that it was holding on to a file handle for the last rotated file (.9) of that container. i *suspect* docker's logging system deleted the .9 file before fluent-bit was able to finish tailing it and somehow fluent-bit is unable to recover from this for that particular container (*i don't know if it's a corner case because of inode reuse*).
```
# sudo lsof -nP -a -p $(pgrep -f fluent-bi[t]) | grep -F b6a4c1b82014
fluent-bi 16157 root   54r      REG  259,1 10000149  814921332 /var/lib/docker/containers/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a-json.log.9 (deleted)
```

workaround (planned):
- change eks docker log-opts to `{"max-size":"100m","max-file":"2"}` to reduce the log file rotation rate.

[fluent-bit-configmap.txt](https://github.com/fluent/fluent-bit/files/2981583/fluent-bit-configmap.txt)
[fluent-bit-ds.txt](https://github.com/fluent/fluent-bit/files/2981584/fluent-bit-ds.txt)

**Comment by mgsh** [comment]
> container logs stop after few hours: when i inspected the file handles held by fluent-bit for a container where it stopped tailing after a few hours, i noticed that it was holding on to a file handle for the last rotated file (.9) of that container. i suspect docker's logging system deleted the .9 file before fluent-bit was able to finish tailing it and somehow fluent-bit is unable to recover from this for that particular container (i don't know if it's a corner case because of inode reuse).

if it helps to investigate, it does seem to recover at some point many hours later (although i missed to capture the exact state of things at the point when it recovered).

**Comment by gaogj** [comment]
> 我们有一个类似的问题，几个小时后，流利位停止跟踪一些应用程序。我们在eks中使用fluent-bit，将日志推送到stackdriver。在进一步调查中，这是我发现的。
> 
> 我们的设置（附带流利位配置）：
> 
> * fluent-bit设置为尾随所有匹配的文件`/var/log/conainers/*.log`。kubernetes负责设置符号链接`/var/log/containers/`并登录`/var/lib/docker/containers/`（通过`/var/log/pods/`）
> * 默认情况下，aws eks使用此`log-opts`设置设置docker `{"max-size":"10m","max-file":"10"}`（in `/etc/docker/daemon.json`）
> 
> 问题：
> 
> 1. **容器日志中的间隙**：当**容器的日志**旋转得太快时（要么保持流畅位以便kubernetes更新符号链接），fluent-bit仍然会拖尾其中一个旋转的文件（*。{1..9} ）。当fluent-bit到处使用该容器的当前日志文件符号链接`/var/log/containers/`时，其间的一些旋转文件永远不会被拖尾（因为`/var/log/containers`只有符号链接指向每个容器的当前日志文件）。我认为这也可以通过检查sqlite db来确认，它为每个日志文件保留一个旋转标志。如果旋转的文件是.2或更高，我认为错过了之间的日志。
> 2. **容器日志在几个小时后停止**：当我检查一个容器的fluent-bit所持有的文件句柄，它在几个小时后停止拖尾时，我注意到它正在抓住最后一个旋转文件的文件句柄（.9）那个容器。我_怀疑_ docker的日志系统在fluent-bit能够完成拖尾之前删除了.9文件，并且某种方式fluent-bit无法从该特定容器中恢复（_我不知道是否因为inode重用而成为一个角落案例_）。
> 
> ```
> # sudo lsof -nP -a -p $(pgrep -f fluent-bi[t]) | grep -F b6a4c1b82014
> fluent-bi 16157 root   54r      REG  259,1 10000149  814921332 /var/lib/docker/containers/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a-json.log.9 (deleted)
> ```
> 解决方法（计划）：
> 
> * 更改eks docker log-opts以`{"max-size":"100m","max-file":"2"}`减少日志文件的旋转速率。
> 
> [fluent-bit-configmap.txt ](https://github.com/fluent/fluent-bit/files/2981583/fluent-bit-configmap.txt)
> [fluent-bit-ds.txt](https://github.com/fluent/fluent-bit/files/2981584/fluent-bit-ds.txt)

I have the same problem

**Comment by gaogj** [comment]
> we have a similar issue where fluent-bit stops tracking a few applications after a few hours. we use fluent-bit in eks, to push logs to stackdriver. on further investigation this is what i found out.
> 
> our setup (fluent-bit configs attached):
> 
> * fluent-bit is set up to tail all files matching `/var/log/conainers/*.log`. kubernetes takes care of setting up symlinks in `/var/log/containers/` and logs in `/var/lib/docker/containers/` (through `/var/log/pods/`)
> * by default, aws eks sets up docker with this `log-opts` setting `{"max-size":"10m","max-file":"10"}` (in `/etc/docker/daemon.json`)
> 
> issues:
> 
> 1. **gaps in container logs**: when logs for a container rotates too fast (either for fluent-bit to keep up or for kubernetes to update symlinks), fluent-bit is still tailing one of the rotated files (*.{1..9}). by the time fluent-bit gets around to use the current log file symlink for that container in `/var/log/containers/`, some rotated files in between are never tailed (because `/var/log/containers` only has symlinks pointing to the current log file for each container). i think this can also be confirmed by examining the sqlite db, where it keeps a rotated flag for every log file. in cases where the rotated file is .2 or higher, i think logs in between were missed.
> 2. **container logs stop after few hours**: when i inspected the file handles held by fluent-bit for a container where it stopped tailing after a few hours, i noticed that it was holding on to a file handle for the last rotated file (.9) of that container. i _suspect_ docker's logging system deleted the .9 file before fluent-bit was able to finish tailing it and somehow fluent-bit is unable to recover from this for that particular container (_i don't know if it's a corner case because of inode reuse_).
> 
> ```
> # sudo lsof -nP -a -p $(pgrep -f fluent-bi[t]) | grep -F b6a4c1b82014
> fluent-bi 16157 root   54r      REG  259,1 10000149  814921332 /var/lib/docker/containers/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a/b6a4c1b82014891feb521f973c2823f3d291595b5a28c04d437093425e61ba7a-json.log.9 (deleted)
> ```
> workaround (planned):
> 
> * change eks docker log-opts to `{"max-size":"100m","max-file":"2"}` to reduce the log file rotation rate.
> 
> [fluent-bit-configmap.txt](https://github.com/fluent/fluent-bit/files/2981583/fluent-bit-configmap.txt)
> [fluent-bit-ds.txt](https://github.com/fluent/fluent-bit/files/2981584/fluent-bit-ds.txt)

I have the same problem

**Comment by edsiper** [comment]
FYI: I've pushed a fix for the root cause of the problem, thanks to everybody who helped to troubleshoot the problem.

ref: https://github.com/fluent/fluent-bit/commit/1ef74fb0674490f665c3139a406896453f4d4a53

**Comment by edsiper** [comment]
Fixed in v1.1.1 release:

https://fluentbit.io/announcements/v1.1.1/

**Comment by haritw** [comment]
@edsiper looks like this issue came back on the latest version (1.2.2)

**Comment by hemalsolgama** [comment]
I am facing the same issue with Fluent bit 1.5..

We have GKE cluster and while using fluent bit for large number of logs, some of the pods just stop working after few hours and everyday we have missing logs of many containers.

I even tried to add file system storage but still there is no luck.. Here is my fluent bit configuration file:

apiVersion: v1
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           Off
        K8S-Logging.Parser  On
        Labels              Off
        K8S-Logging.Exclude Off
  fluent-bit.conf: |
    [SERVICE]
        Flush                     1
        Log_Level                 info
        Daemon                    off
        Parsers_File              parsers.conf
        HTTP_Server               On
        HTTP_Listen               0.0.0.0
        HTTP_Port                 2020
        storage.path              /var/log/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 250M

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Refresh_Interval  2
        Buffer_Max_Size   2G
        Buffer_Chunk_Size 1G
        Parser            docker
        storage.type      filesystem
        Mem_Buf_Limit     250MB
        Docker_Mode       On
  output-elasticsearch.conf: |
    [OUTPUT]
        Name             http
        Match            *
        Host             34.66.212.103
        Port             5044
        Format           json
        Retry_Limit      false
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As  escaped    log

It's been 2 weeks since we implemented fluent bit.. It works fine on our development environment because of less logs however, it doesn't work on production.

Can anyone throw some light over this?

**Comment by xuchenCN** [comment]
@edsiper I still have the problem using v1.8.9
I notice that there has the gap between link log file and orignal log file

```
# ls -l /var/log/pods/xxx/controller/0.log
lrwxrwxrwx 1 root root Nov  8 16:58 /var/log/pods/xxx/controller/0.log -> /home/docker/containers/xxx-json.log

# ls -l /home/docker/containers/xxx-json.log
-rw-r----- 1 root root Nov  9 17:14 /home/docker/containers/xxx-json.log
```

Fluent-bit fetch the link log file and recongize that file dosen't update ?

**Comment by ndhcoder** [comment]
I got same issue at latest version

**Comment by FranciscoPimentel** [comment]
I got same issue at latest version

**Comment by pierluigilenoci** [comment]
@pnl0dg7k @xuchenCN @ndhcoder @FranciscoPimentel, I suggest you open a new issue detailing how to reproduce your specific problem more precisely.
This has now been closed, and commenting here will lead nowhere.
