### ISSUE TITLE
The td-agent-bit image at version 1.8.15 has disappeared from the APT repository

### ISSUE THREAD

**Issue by iyuvalk** [fluent/fluent-bit#6695]
## Bug Report

**Describe the bug**
We have a custom docker image we are building as part of our product which relies on FluentBit at version 1.8.15. This dockerfile starts with `FROM ubuntu:focal` and contains the line `RUN apt-get install -y td-agent-bit=1.8.15` which installs the fluentbit at version 1.8.15 and also builds a custom output plugin. Until today this dockerfile would build successfully and today we started getting this error on the line `RUN apt-get install -y td-agent-bit=1.8.15`:
```
Step 16/24 : RUN apt-get install -y td-agent-bit=1.8.15
 ---> Running in 4f038496c148
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.8.15' for 'td-agent-bit' was not found
The command '/bin/sh -c apt-get install -y td-agent-bit=1.8.15' returned a non-zero code: 100
```

**To Reproduce**
1. Create the following Dockerfile in an empty folder:
```
FROM ubuntu:focal
ENV TZ=Asia/Jerusalem

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y ca-certificates wget gnupg git gcc
RUN echo 'deb https://packages.fluentbit.io/ubuntu/focal focal main' >> /etc/apt/sources.list
RUN wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add -
RUN apt-get update
RUN apt-get install -y td-agent-bit=1.8.15

CMD ["/opt/td-agent-bit/bin/td-agent-bit", "-c", "/etc/td-agent-bit/config/td-agent-bit.conf"]
```
2. cd to that folder and run `docker build .`
3. The following error message will be displayed since today:
```
.
.
.
 ---> 52eb0591416f
Step 9/10 : RUN apt-get install -y td-agent-bit=1.8.15
 ---> Running in 6bab97ee8df1
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.8.15' for 'td-agent-bit' was not found
The command '/bin/sh -c apt-get install -y td-agent-bit=1.8.15' returned a non-zero code: 100
```
- Rubular link if applicable: N/A
- Example log message if applicable: N/A
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem: Written above

**Expected behavior**
As this Dockerfile worked until today, this Dockerfile should build normally.

**Screenshots**
N/A

**Your Environment**
All is available in the Dockerfile above
* Version used:
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
This issue prevents us from building new versions of our product since our product doesn't support newer versions of td-agent-bit at the moment

**Comment by patrick-stephens** [comment]
Likely a result of https://github.com/fluent/fluent-bit/discussions/6688 so let me investigate. The packages should be there so ensure you are resolving the new server correctly as well.

**Comment by HenriBlacksmith** [comment]
Hello, we are facing the same issue on both commands (Amazon Linux and Debian):


```shell
readonly FLUENTBIT_VERSION=1.8.15
sudo apt-get -y install td-agent-bit=${FLUENTBIT_VERSION}
```

```shell
readonly FLUENTBIT_VERSION=1.8.15
sudo yum install -y td-agent-bit-${FLUENTBIT_VERSION}
```

**Comment by patrick-stephens** [comment]
It looks like we have 1.8.13 there but no .14 or .15: https://packages.fluentbit.io/ubuntu/focal/pool/main/t/td-agent-bit/
I will manually sync over and rebuild the indices to get it in.

**Comment by iyuvalk** [comment]
> Likely a result of #6688 so let me investigate. The packages should be there so ensure you are resolving the new server correctly as well.

Tried with this Dockerfile now:
```
FROM ubuntu:focal
ENV TZ=Asia/Jerusalem

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y ca-certificates wget gnupg git gcc
RUN echo 'deb https://packages-next.fluentbit.io/ubuntu/focal focal main' >> /etc/apt/sources.list
RUN wget -qO - https://packages-next.fluentbit.io/fluentbit.key | apt-key add -
RUN apt-get update
RUN apt-get install -y td-agent-bit=1.8.15

CMD ["/opt/td-agent-bit/bin/td-agent-bit", "-c", "/etc/td-agent-bit/config/td-agent-bit.conf"]
```

And the same error was thrown:
```
➜  fb-test docker build . 
Sending build context to Docker daemon   2.56kB
Step 1/10 : FROM ubuntu:focal
 ---> 53df61775e88
Step 2/10 : ENV TZ=Asia/Jerusalem
 ---> Using cache
 ---> 06780972dd16
Step 3/10 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> 9c573951dca3
Step 4/10 : RUN apt-get update
 ---> Using cache
 ---> 592777f73fc0
Step 5/10 : RUN apt-get install -y ca-certificates wget gnupg git gcc
 ---> Using cache
 ---> a675425322d5
Step 6/10 : RUN echo 'deb https://packages-next.fluentbit.io/ubuntu/focal focal main' >> /etc/apt/sources.list
 ---> Running in 1eb83d208501
Removing intermediate container 1eb83d208501
 ---> 3333c1c56e0e
Step 7/10 : RUN wget -qO - https://packages-next.fluentbit.io/fluentbit.key | apt-key add -
 ---> Running in a7d917c7408d
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Removing intermediate container a7d917c7408d
 ---> 8c2ad2577318
Step 8/10 : RUN apt-get update
 ---> Running in 930a68fd6fc0
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:5 https://packages-next.fluentbit.io/ubuntu/focal focal InRelease [7565 B]
Get:6 https://packages-next.fluentbit.io/ubuntu/focal focal/main amd64 Packages [25.1 kB]
Fetched 32.7 kB in 1s (23.1 kB/s)
Reading package lists...
Removing intermediate container 930a68fd6fc0
 ---> 7bd6154481fc
Step 9/10 : RUN apt-get install -y td-agent-bit=1.8.15
 ---> Running in d286cc4ca2d6
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.8.15' for 'td-agent-bit' was not found
The command '/bin/sh -c apt-get install -y td-agent-bit=1.8.15' returned a non-zero code: 100
```

**Comment by patrick-stephens** [comment]
Yes, see my comment above. 1.8.15 is not present in the repo so I will add it.

**Comment by iyuvalk** [comment]
Cool @patrick-stephens. You replied faster than I could type.... (:

**Comment by patrick-stephens** [comment]
No worries, I've been keeping an eye out for any issues after the switchover today hence why I caught it so quick! :)

Again, apologies for that - it might take a little while to get the packages back up so please bear with, plus I want to make sure it is not rushed but done properly with no other impact.

**Comment by patrick-stephens** [comment]
@iyuvalk I think this should be resolved now, it seems to work for me anyway so please double check any caches, etc. as well.

**Comment by kwakwakwak** [comment]
Hi, following up on @HenriBlacksmith's comment, we still face the issue on Debian (Amazon Linux is working fine). Did you rebuilt the indexes for Debian ? Thanks a lot

**Comment by kwakwakwak** [comment]
We still get this error when trying to install 1.8.15 when building an AMI, with:

```
readonly FLUENTBIT_VERSION=1.8.15
sudo curl https://packages-next.fluentbit.io/fluentbit.key | sudo apt-key add -
echo "deb https://packages-next.fluentbit.io/debian/stretch stretch main" | sudo tee -a /etc/apt/sources.list
sudo apt-get -y update
sudo apt-get -y install td-agent-bit=${FLUENTBIT_VERSION}
```

I reproduced the error on a Debian docker below:

```
root@0e1edd22f92a:/# curl https://packages-next.fluentbit.io/fluentbit.key | apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  3175  100  3175    0     0   6614      0 --:--:-- --:--:-- --:--:--  6600
OK
root@0e1edd22f92a:/# echo "deb https://packages-next.fluentbit.io/debian/stretch stretch main" | tee -a /etc/apt/sources.list
deb https://packages-next.fluentbit.io/debian/stretch stretch main
root@0e1edd22f92a:/#  apt-get -y update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian-security bullseye-security InRelease
Get:3 https://packages-next.fluentbit.io/debian/stretch stretch InRelease [5301 B]
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Get:5 https://packages-next.fluentbit.io/debian/stretch stretch/main amd64 Packages [995 B]
Fetched 6296 B in 1s (6128 B/s)
Reading package lists... Done
root@0e1edd22f92a:/# apt-get -y install td-agent-bit=1.8.15
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Version '1.8.15' for 'td-agent-bit' was not found
```

**Comment by patrick-stephens** [comment]
Yeah, it's related to #6701 - I added the deps but did not realise the update script no longer covers stretch so I will rebuild that index.

**Comment by patrick-stephens** [comment]
Should be resolved now @kwakwakwak: https://github.com/fluent/fluent-bit/issues/6701#issuecomment-1386830374

**Comment by kwakwakwak** [comment]
Yes it's working perfectly on our side now! Thanks a lot :)
